USE [master]
GO

/****** Object:  Database [Estoque]    Script Date: 24/03/2021 02:09:10 ******/
CREATE DATABASE [Estoque]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Estoque', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Estoque.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Estoque_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Estoque_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Estoque].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Estoque] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Estoque] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Estoque] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Estoque] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Estoque] SET ARITHABORT OFF 
GO

ALTER DATABASE [Estoque] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Estoque] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Estoque] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Estoque] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Estoque] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Estoque] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Estoque] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Estoque] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Estoque] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Estoque] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Estoque] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Estoque] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Estoque] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Estoque] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Estoque] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Estoque] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Estoque] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Estoque] SET RECOVERY FULL 
GO

ALTER DATABASE [Estoque] SET  MULTI_USER 
GO

ALTER DATABASE [Estoque] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Estoque] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Estoque] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Estoque] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Estoque] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Estoque] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Estoque] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Estoque] SET  READ_WRITE 
GO


